### ISSUE TITLE
Doubts about Figure S12

### ISSUE THREAD

**Issue by hml1996-fight** [Gonglab-THU/SPIRED-Fitness#2]
Dear author, @Gonglab-THU ：
  As far as i know, The smaller the ddg-value, the better. the larger the dTM value, the better. 
  
![image](https://github.com/user-attachments/assets/3ca7d68a-0d62-4878-9dce-ad0eabd5ec4b)
In this picture, Did you reverse the ddG?

**Comment by hml1996-fight** [comment]
![image](https://github.com/user-attachments/assets/8be4e0c0-e181-47eb-b0ea-fae9dd9a3b1d)

**Comment by Gonglab-THU** [comment]
Yes, we reverse the ddG value in the Figure S12. Thank you.

**Comment by Gonglab-THU** [comment]
Hi, Dear Readers, @hml1996-fight :
     In our entire article, the definitions of ddG and dTm are as follows: The more stable the mutated protein, the larger the ddG. The more stable the mutated protein, the larger the dTm. 
     Therefore, in Figure S12, ddG and dTm are positively correlated. 
     The definition of ddG we follow is given by the formula below. Hence, as the mutation becomes more stable, both dG(mut) and ddG increase.
![image](https://github.com/user-attachments/assets/46605138-74e5-4a1f-8bf1-fab6d43d0d6a)

**Comment by hml1996-fight** [comment]
OK! I understand. Thank you.
