### ISSUE TITLE
The data used in the first stage of SPIRED-Stab

### ISSUE THREAD

**Issue by goes0n** [Gonglab-THU/SPIRED-Fitness#3]
It seems that the data used in the first stage of SPIRED-Stab is the inferred ddG/dTm from cDNA proteolysis datasets? Can you provide these data? I can not find it in zenodo. Thanks a lot!!

**Comment by Gonglab-THU** [comment]
The cDNA proteolysis datasets we used are from the literature [Mega-scale experimental analysis of protein folding stability in biology and design](https://doi.org/10.1038/s41586-023-06328-6). The link to the dataset of the literature can be found in [Zenodo](https://zenodo.org/doi/10.5281/zenodo.7401274).
