### ISSUE TITLE
Can SPIRED Predict Multi-chain Structures?

### ISSUE THREAD

**Issue by jong3** [Gonglab-THU/SPIRED-Fitness#6]
Hi,

I have a question regarding the structure modeling software SPIRED. Can it predict multi-chain structures, or is it limited to single-chain predictions?

Thank you!

**Comment by Gonglab-THU** [comment]
Hi @jong3 

SPIRD is trained on single-chain protein structure data and currently may not have the capability to predict the structures of multi-chain proteins. Our laboratory is in the process of training a model for multi-chain protein structure prediction.
